# Generated by Django 5.0.6 on 2024-07-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='titlle',
            new_name='title',
        ),
    ]
